-- MySQL Script generated by MySQL Workbench
-- Fri Feb 23 09:53:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alexno92_devaction
-- -----------------------------------------------------
 -- DROP SCHEMA IF EXISTS `alexno92_devaction` ;

-- -----------------------------------------------------
-- Schema alexno92_devaction
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alexno92_devaction` DEFAULT CHARACTER SET utf8 ;
USE `alexno92_devaction` ;

-- -----------------------------------------------------
-- Table `alexno92_devaction`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexno92_devaction`.`empresa` ;

CREATE TABLE IF NOT EXISTS `alexno92_devaction`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `razaosocial` VARCHAR(80) NOT NULL,
  `nomefantasia` VARCHAR(80) NULL,
  `CNPJ` VARCHAR(18) NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexno92_devaction`.`vaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexno92_devaction`.`vaga` ;

CREATE TABLE IF NOT EXISTS `alexno92_devaction`.`vaga` (
  `idvaga` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `FK_idempresa` INT NOT NULL,
  PRIMARY KEY (`idvaga`),
  INDEX `fk_vaga_empresa1_idx` (`FK_idempresa` ASC),
  CONSTRAINT `fk_vaga_empresa1`
    FOREIGN KEY (`FK_idempresa`)
    REFERENCES `alexno92_devaction`.`empresa` (`idempresa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexno92_devaction`.`tecnologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexno92_devaction`.`tecnologia` ;

CREATE TABLE IF NOT EXISTS `alexno92_devaction`.`tecnologia` (
  `idtecnologia` INT NOT NULL AUTO_INCREMENT,
  `tecnologia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtecnologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alexno92_devaction`.`tecnologiasporvaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alexno92_devaction`.`tecnologiasporvaga` ;

CREATE TABLE IF NOT EXISTS `alexno92_devaction`.`tecnologiasporvaga` (
  `FK_idtecnologia` INT NOT NULL,
  `FK_idvaga` INT NOT NULL,
  PRIMARY KEY (`FK_idtecnologia`, `FK_idvaga`),
  INDEX `fk_tecnologia_has_vaga_vaga1_idx` (`FK_idvaga` ASC),
  INDEX `fk_tecnologia_has_vaga_tecnologia1_idx` (`FK_idtecnologia` ASC),
  CONSTRAINT `fk_tecnologia_has_vaga_tecnologia1`
    FOREIGN KEY (`FK_idtecnologia`)
    REFERENCES `alexno92_devaction`.`tecnologia` (`idtecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tecnologia_has_vaga_vaga1`
    FOREIGN KEY (`FK_idvaga`)
    REFERENCES `alexno92_devaction`.`vaga` (`idvaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
